import { Annotations, Duration } from 'aws-cdk-lib'
import { CfnQueue, Queue, IQueue } from 'aws-cdk-lib/aws-sqs'
import { SqsEventSource } from 'aws-cdk-lib/aws-lambda-event-sources'
import {
  Function as LambdaFunction,
  Code,
  Architecture,
  Runtime,
  Tracing
} from 'aws-cdk-lib/aws-lambda'
import { IRole, Role, ServicePrincipal, ManagedPolicy } from 'aws-cdk-lib/aws-iam'
import { LogGroup } from 'aws-cdk-lib/aws-logs'
import { ITopic } from 'aws-cdk-lib/aws-sns'
import { SqsSubscription, SqsSubscriptionProps } from 'aws-cdk-lib/aws-sns-subscriptions'
import { Construct } from 'constructs'
import { Stage, VpcConfig } from '../types'
import { applyStandardTags } from '../utils/tagging'
import { getLogRetentionDays, getRemovalPolicy } from '../utils/logs'
import { buildBaseEnvironment, buildRecapDevEnvironment, resolveRecapDevEndpoint } from '../utils/config'
import { DEFAULT_LAMBDA_RUNTIME } from '../utils/constants'
import { generateLambdaName } from '../utils/naming'
import { resolveHandlerPath } from '../utils/handler-path'
import { makeSnsToSqsSubscription, overrideFunctionLogicalIds } from '../utils/serverless-migration'
import { DlqAlarm } from './dlq-alarm'

export interface LambdaWithQueueProps {
  /** Lambda function name. Optional when `handlerPath` is provided. */
  readonly functionName?: string
  readonly queueName: string
  /** Short name used for codePath default and alarm naming. Defaults to functionName. */
  readonly resourceName?: string
  readonly handler?: string
  readonly codePath?: string
  /**
   * Source handler path, same as `EmStack.createFunction()`.
   * Derives `functionName`, `handler`, and `codePath` from the path.
   */
  readonly handlerPath?: string
  readonly reservedConcurrency?: number
  readonly batchSize?: number
  readonly reportBatchItemFailures?: boolean
  readonly stage: Stage
  readonly serviceName: string
  readonly environment?: Record<string, string>
  /** Lambda memory in MB. Defaults to 1024. */
  readonly memorySize?: number
  /** Lambda timeout. Defaults to 15 seconds. */
  readonly timeout?: Duration
  /** Enable X-Ray tracing. Defaults to true. */
  readonly enableTracing?: boolean
  readonly tags?: Record<string, string>
  /** IAM role name. Required when `role` is not provided. */
  readonly roleName?: string
  /** Provide an existing IAM role instead of creating one. When set, `roleName` is ignored. */
  readonly role?: IRole
  readonly alarmTopic: ITopic
  /** Override DLQ name. Defaults to `{queueName}-dlq`. */
  readonly dlqName?: string
  /** Override alarm name. Defaults to `{stage}-{serviceName}-{resourceName}-dlq-alarm`. */
  readonly alarmName?: string
  readonly additionalQueues?: IQueue[]
  readonly maxReceiveCount?: number
  /** Override queue visibility timeout. Defaults to `max(30s, timeout * 3)`. */
  readonly visibilityTimeout?: Duration
  readonly maxBatchingWindow?: Duration
  readonly maxConcurrency?: number
  readonly vpcConfig?: VpcConfig
  readonly architecture?: Architecture
  readonly runtime?: Runtime
  /**
   * Migration-only: use this exact Lambda function name instead of the name
   * generated by `generateLambdaName()`.
   *
   * This is needed when an existing Serverless function uses a legacy physical
   * name that CDK must keep during migration. The same name is also used for the
   * Lambda log group path.
   *
   * This does not change the CloudFormation logical ID. For Serverless migrations,
   * also set `serverlessFunctionName` when the Lambda and log group logical IDs
   * need to match the existing Serverless stack.
   *
   * See `LambdaConfig.physicalName` for the same migration caveat used by
   * `EmStack.createFunction()`.
   */
  readonly physicalName?: string
  /**
   * Migration-only: Serverless function name for logical ID overrides.
   * Overrides Lambda + log group logical IDs to match Serverless Framework naming.
   */
  readonly serverlessFunctionName?: string
  /**
   * Override CloudFormation logical IDs for queue resources (migration mode).
   */
  readonly overrideLogicalIds?: {
    readonly queue?: string
    readonly dlq?: string
    readonly alarm?: string
  }
}

export class LambdaWithQueue extends Construct {
  public readonly function: LambdaFunction

  public readonly queue: Queue

  public readonly dlq: Queue

  public readonly dlqAlarm: DlqAlarm

  constructor(scope: Construct, id: string, props: LambdaWithQueueProps) {
    super(scope, id)

    const resolved = resolveHandlerPath(props)
    const shortName = resolved.functionName
    const resourceName = props.resourceName ?? shortName
    const functionName = props.physicalName ?? generateLambdaName(props.stage, props.serviceName, shortName)
    const handler = resolved.handler ?? props.handler ?? 'index.handler'
    const codePath = resolved.codePath ?? props.codePath ?? `./dist/handlers/${resourceName}`

    if (props.reservedConcurrency === 0) {
      throw new Error(
        `reservedConcurrency:0 disables the Lambda entirely for ${shortName}. Omit the prop to use account-level concurrency.`
      )
    }

    const {
      batchSize = 10,
      reportBatchItemFailures = true,
      additionalQueues = [],
      maxReceiveCount = 3
    } = props

    const memorySize = props.memorySize ?? 1024
    const timeout = props.timeout ?? Duration.seconds(15)
    const enableTracing = props.enableTracing ?? true

    this.dlq = new Queue(this, 'DLQ', {
      queueName: props.dlqName ?? `${props.queueName}-dlq`,
      retentionPeriod: Duration.days(14),
      removalPolicy: getRemovalPolicy(props.stage)
    })

    this.queue = new Queue(this, 'Queue', {
      queueName: props.queueName,
      visibilityTimeout:
        props.visibilityTimeout ?? Duration.seconds(Math.max(30, timeout.toSeconds() * 3)),
      retentionPeriod: Duration.days(4),
      deadLetterQueue: {
        queue: this.dlq,
        maxReceiveCount
      },
      removalPolicy: getRemovalPolicy(props.stage)
    })

    const role: IRole = props.role ?? this.createRole(props, enableTracing)

    const logGroup = new LogGroup(this, 'LogGroup', {
      logGroupName: `/aws/lambda/${functionName}`,
      retention: getLogRetentionDays(props.stage),
      removalPolicy: getRemovalPolicy(props.stage)
    })

    this.function = new LambdaFunction(this, 'Function', {
      functionName,
      runtime: props.runtime ?? DEFAULT_LAMBDA_RUNTIME,
      handler,
      code: Code.fromAsset(codePath),
      architecture: props.architecture ?? Architecture.ARM_64,
      memorySize,
      timeout,
      environment: {
        ...buildBaseEnvironment(props.stage, this),
        ...(props.environment ?? {}),
        ...buildRecapDevEnvironment(resolveRecapDevEndpoint(this))
      },
      role,
      reservedConcurrentExecutions: props.reservedConcurrency,
      tracing: enableTracing ? Tracing.ACTIVE : Tracing.DISABLED,
      logGroup,
      ...(props.vpcConfig && {
        vpc: props.vpcConfig.vpc,
        vpcSubnets: props.vpcConfig.vpcSubnets,
        securityGroups: props.vpcConfig.securityGroups
      })
    })

    this.function.addEventSource(
      new SqsEventSource(this.queue, {
        batchSize,
        reportBatchItemFailures,
        ...(props.maxBatchingWindow && { maxBatchingWindow: props.maxBatchingWindow }),
        ...(props.maxConcurrency !== undefined && { maxConcurrency: props.maxConcurrency })
      })
    )

    applyStandardTags(this.function, {
      stage: props.stage,
      serviceName: props.serviceName,
      customTags: props.tags
    })

    applyStandardTags(this.queue, {
      stage: props.stage,
      serviceName: props.serviceName,
      customTags: props.tags
    })

    applyStandardTags(this.dlq, {
      stage: props.stage,
      serviceName: props.serviceName,
      customTags: props.tags
    })

    this.dlqAlarm = new DlqAlarm(this, 'DLQAlarm', {
      dlq: this.dlq,
      alarmName: props.alarmName ?? `${props.stage}-${props.serviceName}-${resourceName}-dlq-alarm`,
      alarmTopic: props.alarmTopic,
      alarmLogicalId: props.overrideLogicalIds?.alarm
    })

    additionalQueues.forEach(queue => {
      queue.grantSendMessages(this.function)
      queue.grantConsumeMessages(this.function)
    })

    // Serverless migration: override logical IDs
    if (props.serverlessFunctionName) {
      overrideFunctionLogicalIds(this.function, props.serverlessFunctionName)
    }

    if (props.overrideLogicalIds?.queue) {
      const cfnQueue = this.queue.node.defaultChild
      if (!(cfnQueue instanceof CfnQueue)) {
        throw new Error(
          `Cannot override queue logical ID to "${props.overrideLogicalIds.queue}": queue does not have a CfnQueue default child.`
        )
      }
      cfnQueue.overrideLogicalId(props.overrideLogicalIds.queue)
    }

    if (props.overrideLogicalIds?.dlq) {
      const cfnDlq = this.dlq.node.defaultChild
      if (!(cfnDlq instanceof CfnQueue)) {
        throw new Error(
          `Cannot override DLQ logical ID to "${props.overrideLogicalIds.dlq}": DLQ does not have a CfnQueue default child.`
        )
      }
      cfnDlq.overrideLogicalId(props.overrideLogicalIds.dlq)
    }
  }

  private createRole(props: LambdaWithQueueProps, enableTracing: boolean): IRole {
    if (!props.roleName) {
      throw new Error('LambdaWithQueue requires either `role` or `roleName` to be provided.')
    }

    const role = new Role(this, 'Role', {
      roleName: props.roleName,
      assumedBy: new ServicePrincipal('lambda.amazonaws.com'),
      description: `Lambda execution role for ${props.serviceName}`
    })

    role.addManagedPolicy(
      ManagedPolicy.fromAwsManagedPolicyName('service-role/AWSLambdaBasicExecutionRole')
    )

    if (props.vpcConfig) {
      role.addManagedPolicy(
        ManagedPolicy.fromAwsManagedPolicyName('service-role/AWSLambdaVPCAccessExecutionRole')
      )
    }

    if (enableTracing) {
      role.addManagedPolicy(
        ManagedPolicy.fromAwsManagedPolicyName('AWSXRayDaemonWriteAccess')
      )
    }

    return role
  }

  public subscribeToTopic(
    topic: ITopic,
    options?: SqsSubscriptionProps,
    serverlessSubscriptionLogicalId?: string
  ): void {
    if (serverlessSubscriptionLogicalId !== undefined) {
      const trimmed = serverlessSubscriptionLogicalId.trim()
      if (!trimmed) {
        throw new Error(
          'subscribeToTopic: serverlessSubscriptionLogicalId must not be an empty string — ' +
            'omit the argument to use the standard CDK subscription path.'
        )
      }
      if (options?.filterPolicy || options?.filterPolicyWithMessageBody || options?.deadLetterQueue) {
        throw new Error(
          'subscribeToTopic: filterPolicy, filterPolicyWithMessageBody, and deadLetterQueue are not ' +
            'supported with serverlessSubscriptionLogicalId. Use the standard CDK subscription path instead.'
        )
      }
      Annotations.of(this).addWarning(
        `subscribeToTopic with serverlessSubscriptionLogicalId="${trimmed}" ` +
          'creates only the SNS subscription — no SQS queue policy is created. ' +
          'On migrated stacks the queue policy already exists in CloudFormation; ' +
          'preserve it with makeServerlessQueuePolicy(). ' +
          'On new queues you must also call makeServerlessQueuePolicy() or SNS delivery will fail silently.'
      )
      makeSnsToSqsSubscription(this, trimmed, {
        topicArn: topic.topicArn,
        endpoint: this.queue.queueArn,
        protocol: 'sqs',
        rawMessageDelivery: options?.rawMessageDelivery
      })
    } else {
      topic.addSubscription(new SqsSubscription(this.queue, options))
    }
  }
}
